name: local-web-commerce
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-devuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-devpass123}
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - devnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-P@ssw0rd1234!}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      # Simple TCP check to ensure TDS port is accepting connections
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 60s
    networks:
      - devnet
  
  api-accounts:
    image: jgaonaakm/jericalla-mobile-api-accounts:1.0.0-arm
    container_name: api-accounts
    restart: unless-stopped
    ports:
      - "5006:8080"    # AMQP
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  rabbitmq_data:
  mssql_data:
